// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUBALQScAffI9Ny2_Qn8UBJvla9wE7uuE',
    appId: '1:355703054506:web:70878bb72e0641bac0f0d3',
    messagingSenderId: '355703054506',
    projectId: 'learndaily-ceef9',
    authDomain: 'learndaily-ceef9.firebaseapp.com',
    storageBucket: 'learndaily-ceef9.firebasestorage.app',
    measurementId: 'G-VVMNVSWE8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQXtNfsa82phRjutr5tGKXX5KKHZU1gJM',
    appId: '1:355703054506:android:622df40e720ebe71c0f0d3',
    messagingSenderId: '355703054506',
    projectId: 'learndaily-ceef9',
    storageBucket: 'learndaily-ceef9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2B1FR2scD3UuYQS0xDR7sR232gyezDPI',
    appId: '1:355703054506:ios:2c71e22a6c209b05c0f0d3',
    messagingSenderId: '355703054506',
    projectId: 'learndaily-ceef9',
    storageBucket: 'learndaily-ceef9.firebasestorage.app',
    iosBundleId: 'com.example.learndaily',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2B1FR2scD3UuYQS0xDR7sR232gyezDPI',
    appId: '1:355703054506:ios:2c71e22a6c209b05c0f0d3',
    messagingSenderId: '355703054506',
    projectId: 'learndaily-ceef9',
    storageBucket: 'learndaily-ceef9.firebasestorage.app',
    iosBundleId: 'com.example.learndaily',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUBALQScAffI9Ny2_Qn8UBJvla9wE7uuE',
    appId: '1:355703054506:web:ba20ef2dcdb5e4f3c0f0d3',
    messagingSenderId: '355703054506',
    projectId: 'learndaily-ceef9',
    authDomain: 'learndaily-ceef9.firebaseapp.com',
    storageBucket: 'learndaily-ceef9.firebasestorage.app',
    measurementId: 'G-S5JX0DYQPC',
  );
}
